// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthResponse = { access_token: string, refresh_token: string, access_token_expires_at: string, email: string, };
