// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostWriteRequest = { name: string, host: string, port: number, username: string, ssh_key_id: string | null, encrypted_password: string | null, group_id: string | null, };
