// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyUpdateRequest = { name: string, kind: string, fingerprint?: string | null, encrypted_private_key?: string | null, encrypted_passphrase?: string | null, };
