// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortForwardMappingInput = { bind_host: string, bind_port: number, target_host: string, target_port: number, };
