// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortForwardMappingInput } from "./port-forward-mapping-input";

export type PortForwardRecord = { id: string, name: string, host_id: string, host_name: string, mappings: Array<PortForwardMappingInput>, };
