// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnippetRecord = { id: string, host_id: string, host_name: string, title: string, body: string, };
