// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshKeyRecord = { id: string, name: string, kind: string, fingerprint: string | null, };
