// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshHostAuthMaterial } from "./ssh-host-auth-material";

export type SshHostRecord = { id: string, name: string, host: string, port: number, username: string, ssh_key_id: string | null, group_id: string | null, auth: SshHostAuthMaterial | null, };
