
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async getSetting(key: string) : Promise<Setting | null> {
    return await TAURI_INVOKE("get_setting", { key });
},
async setSetting(setting: Setting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { setting }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async getAllSettings() : Promise<Setting[]> {
    return await TAURI_INVOKE("get_all_settings");
},
async sshConnect(host: string, port: number, user: string, auth: AuthMethodInput, cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_connect", { host, port, user, auth, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localConnect(cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_connect", { cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthMethodInput = { type: "password"; password: string } | { type: "key"; key_path: string }
export type Setting = { key: string; value: string }

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };
