
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async sshConnectDirect(input: DirectSshConnectInput, cols: number, rows: number) : Promise<Result<SshConnectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_connect_direct", { input, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshConfirmHostTrust(confirmation: HostTrustConfirmation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_confirm_host_trust", { confirmation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localConnect(cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_connect", { cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type DirectSshConnectInput = { host: string; port: number; username: string; password: string | null; private_key: string | null; passphrase: string | null }
export type HostTrustConfirmation = { host: string; port: number; algorithm: string; fingerprint: string }
export type HostTrustMismatch = { host: string; port: number; expected_algorithm: string; expected_fingerprint: string; presented_algorithm: string; presented_fingerprint: string }
export type HostTrustPrompt = { host: string; port: number; algorithm: string; fingerprint: string }
export type SshConnectResponse = { status: "connected"; session_id: string } | { status: "trust_required"; prompt: HostTrustPrompt } | { status: "trust_mismatch"; mismatch: HostTrustMismatch }

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };
