
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshConnectDirect(input: DirectSshConnectInput, cols: number, rows: number) : Promise<Result<SshConnectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_connect_direct", { input, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshConfirmHostTrust(confirmation: HostTrustConfirmation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_confirm_host_trust", { confirmation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshProbeHostInfo(input: DirectSshConnectInput) : Promise<Result<SshProbeHostInfoResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_probe_host_info", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshStartLocalPortForward(input: SshLocalPortForwardInput) : Promise<Result<SshPortForwardStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_start_local_port_forward", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async sshStopPortForward(sessionId: string, forwardId: string) : Promise<Result<SshPortForwardStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_stop_port_forward", { sessionId, forwardId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localConnect(cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_connect", { cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localWrite(sessionId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localResize(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async localDisconnect(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_disconnect", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async portForwardStart(input: PortForwardStartInput) : Promise<Result<PortForwardStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("port_forward_start", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async portForwardStop(forwardId: string) : Promise<Result<PortForwardStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("port_forward_stop", { forwardId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async portForwardList() : Promise<Result<PortForwardStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("port_forward_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async knownHostsGet() : Promise<Result<KnownHostsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("known_hosts_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
},
async knownHostsRemove(host: string, port: number) : Promise<Result<KnownHostsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("known_hosts_remove", { host, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: String(e) };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { api_url: string }
export type DirectSshConnectInput = { host: string; port: number; username: string; password: string | null; private_key: string | null; passphrase: string | null }
export type HostSystemInfo = { hostname: string | null; os: string | null; cpu_usage_percent: number | null; memory_total_bytes: number | null; memory_used_bytes: number | null; memory_usage_percent: number | null; disk_read_bytes_per_second: number | null; disk_write_bytes_per_second: number | null; network_rx_bytes_per_second: number | null; network_tx_bytes_per_second: number | null }
export type HostTrustConfirmation = { host: string; port: number; algorithm: string; fingerprint: string }
export type HostTrustMismatch = { host: string; port: number; expected_algorithm: string; expected_fingerprint: string; presented_algorithm: string; presented_fingerprint: string }
export type HostTrustPrompt = { host: string; port: number; algorithm: string; fingerprint: string }
export type KnownHostsResponse = { hosts: TrustedSshHost[] }
export type PortForwardStartInput = { name: string; host: string; port: number; username: string; password: string | null; private_key: string | null; passphrase: string | null; bind_host: string; bind_port: number; target_host: string; target_port: number }
export type PortForwardState = "connecting" | "listening" | "stopped" | "error"
export type PortForwardStatus = { id: string; name: string; host: string; port: number; username: string; bind_host: string; bind_port: number; target_host: string; target_port: number; state: PortForwardState; error: string | null }
export type SshConnectResponse = { status: "connected"; session_id: string } | { status: "trust_required"; prompt: HostTrustPrompt } | { status: "trust_mismatch"; mismatch: HostTrustMismatch }
export type SshLocalPortForwardInput = { session_id: string; bind_host: string; bind_port: number; target_host: string; target_port: number }
export type SshPortForwardState = "listening" | "stopped" | "error"
export type SshPortForwardStatus = { forward_id: string; session_id: string; bind_host: string; bind_port: number; target_host: string; target_port: number; status: SshPortForwardState; error: string | null }
export type SshProbeHostInfoResponse = { status: "success"; info: HostSystemInfo } | { status: "trust_required"; prompt: HostTrustPrompt } | { status: "trust_mismatch"; mismatch: HostTrustMismatch }
export type TrustedSshHost = { host: string; port: number; algorithm: string; fingerprint: string }

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };
