// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async greet(name: string): Promise<string> {
    return await TAURI_INVOKE("greet", { name });
  },
  async getSetting(key: string): Promise<Setting | null> {
    return await TAURI_INVOKE("get_setting", { key });
  },
  async setSetting(setting: Setting): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_setting", { setting }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: String(e) };
    }
  },
  async getAllSettings(): Promise<Setting[]> {
    return await TAURI_INVOKE("get_all_settings");
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type Setting = { key: string; value: string };

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };
